/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entity.*;
import controller.*;
import java.util.Collection;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author nathanbispo
 */
public class TelaVenda extends javax.swing.JFrame {
    
    ControllerVenda venda = new ControllerVenda();
    LinkedList<Produto> listProduto;
    
    /*
    ** Lista para teste
    
    LinkedList<Produto> listTestePRODUTO;
    public LinkedList<Produto> instanciaTestePRODUTO(){
        listTestePRODUTO = new LinkedList<>();
        listTestePRODUTO.add(new Produto(2, "Barbie", 100.2));
        listTestePRODUTO.add(new Produto(3, "Nerf", 325.6));
        listTestePRODUTO.add(new Produto(4, "Caminhao", 53.4));
        listTestePRODUTO.add(new Produto(5, "Aviao", 214.8));
        listTestePRODUTO.add(new Produto(6, "Barco", 100.0));
        listTestePRODUTO.add(new Produto(7, "Boomerang", 19.9));
        return listTestePRODUTO;
    }
    
    Collection<ItemDeVenda> listTesteITENS;
    public LinkedList<ItemDeVenda> instanciaTesteITENS(){
        listTesteITENS = new LinkedList<>();
        listTesteITENS.add(new ItemDeVenda(new Produto(2, "Barbie", 100.2)));
        listTesteITENS.add(new ItemDeVenda(new Produto(3, "Nerf", 325.6)));
        listTesteITENS.add(new ItemDeVenda(new Produto(4, "Caminhao", 53.4)));
        listTesteITENS.add(new ItemDeVenda(new Produto(5, "Aviao", 214.8)));
        listTesteITENS.add(new ItemDeVenda(new Produto(6, "Barco", 100.0)));
        listTesteITENS.add(new ItemDeVenda(new Produto(7, "Boomerang", 19.9)));
        return (LinkedList<ItemDeVenda>)listTesteITENS;
    }
    */
    
    /**
     * Creates new form OlaMundoJava
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        codDeBarrasLABEL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        codDeBarrasCAMPO = new javax.swing.JTextArea();
        nomeNomeLABEL = new javax.swing.JLabel();
        listaDeCompraLABEL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nomeTEXTO = new javax.swing.JTextArea();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cargo = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JLabel();
        qtd = new javax.swing.JSpinner();
        finalizarVenda = new javax.swing.JButton();
        cancelarVenda = new javax.swing.JButton();
        valorTotalLABEL = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codDeBarrasLABEL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        codDeBarrasLABEL.setForeground(new java.awt.Color(50, 50, 50));
        codDeBarrasLABEL.setText("Cod. de Barras");
        codDeBarrasLABEL.setToolTipText("");

        codDeBarrasCAMPO.setColumns(20);
        codDeBarrasCAMPO.setRows(5);
        jScrollPane2.setViewportView(codDeBarrasCAMPO);

        nomeNomeLABEL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeNomeLABEL.setForeground(new java.awt.Color(50, 50, 50));
        nomeNomeLABEL.setText("Nome");
        nomeNomeLABEL.setToolTipText("");

        listaDeCompraLABEL.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        listaDeCompraLABEL.setForeground(new java.awt.Color(50, 50, 50));
        listaDeCompraLABEL.setText("Lista de compras");

        nomeTEXTO.setColumns(20);
        nomeTEXTO.setRows(5);
        jScrollPane3.setViewportView(nomeTEXTO);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        listaProdutos.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        listaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Qtd", "Nome", "Preço Uni.", "Preço Parcial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listaProdutos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listaProdutos);

        jPanel1.setBackground(new java.awt.Color(0, 191, 255));

        cargo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cargo.setForeground(new java.awt.Color(250, 250, 250));
        cargo.setText("Vendedor");

        nomeFuncionario.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nomeFuncionario.setForeground(new java.awt.Color(250, 250, 250));
        nomeFuncionario.setText("Nome Funcionario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        finalizarVenda.setBackground(new java.awt.Color(0, 255, 0));
        finalizarVenda.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        finalizarVenda.setForeground(new java.awt.Color(255, 255, 255));
        finalizarVenda.setText("Finalizar Venda");
        finalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarVendaActionPerformed(evt);
            }
        });

        cancelarVenda.setBackground(new java.awt.Color(255, 0, 0));
        cancelarVenda.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        cancelarVenda.setForeground(new java.awt.Color(255, 255, 255));
        cancelarVenda.setText("Cancelar Venda");
        cancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVendaActionPerformed(evt);
            }
        });

        valorTotalLABEL.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        valorTotalLABEL.setForeground(new java.awt.Color(50, 50, 50));
        valorTotalLABEL.setText("R$ 0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(listaDeCompraLABEL)
                                .addGap(512, 512, 512))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 292, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomeNomeLABEL)
                                    .addComponent(codDeBarrasLABEL))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(finalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(valorTotalLABEL)
                                .addGap(29, 29, 29)))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(codDeBarrasLABEL))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeNomeLABEL)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar)
                    .addComponent(qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(listaDeCompraLABEL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(valorTotalLABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setTamanhoTabelaPopUp(){
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
        new String [] {
            "Id", "Nome", "Preco", "Title 4"
        }));
    }
    
    String idString = "";
    private String listaProdutosPOPUP(LinkedList<Produto> list){
        idString = "";
        //criar POPUP
        JFrame janela = new JFrame();
        JButton botao = new javax.swing.JButton("ENVIAR");
        
        JTextArea textArea = new JTextArea();
                
        janela.setSize(500, 800);        
        janela.setTitle("Lista de Produtos");
        janela.setLocationRelativeTo(null); // para aparecer no meio da tela
        janela.setVisible(true);
  
        botao.setBounds(290,700,100, 50);
        janela.add(botao);
        textArea.setBounds(80,700,240, 50);
        janela.add(textArea);
        
        setTamanhoTabelaPopUp();
        //add cabeçalho na primeira linha da tabela
        jTable1.setValueAt("ID", 0, 0);
        jTable1.setValueAt("NOME", 0, 1);
        jTable1.setValueAt("PREÇO", 0, 2);
        //jTable1.setValueAt(botao, 0, 3);
        
        //coloca valores da lista na tabela jTable1
        int linha=1;
        //list = instanciaTestePRODUTO();
        for (Produto prod : list) {
            jTable1.setValueAt(prod.getCodigoBarras(), linha, 0);
            jTable1.setValueAt(prod.getNomeProduto(), linha, 1);
            jTable1.setValueAt(prod.getPreco(), linha, 2);
            linha++;
        }
             
        //add tabela jTable1 no POPUP
        janela.add(jTable1);
        
        botao.addActionListener((java.awt.event.ActionEvent evt) -> {
            idString = textArea.getText();
            janela.setVisible(false);
        });
        return idString;
        
    }

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        int id = 0;
        Collection<ItemDeVenda> listProdutoVenda;
        Produto produto;
        
        //pega String do campo de codigo de barras
        if(!codDeBarrasCAMPO.getText().equals("")){
           String idCampo = codDeBarrasCAMPO.getText();
           id = Integer.parseInt(idCampo);
        }
        /*
        ** pega String do campo de nome
        ** chama o metodo para buscar produto por nome que retorna um int id
        */
        else if(!nomeTEXTO.getText().equals("")){
            String nomeCampo = nomeTEXTO.getText();
            listProduto = (LinkedList<Produto>) venda.buscarProduto(nomeCampo);
            id = Integer.parseInt(listaProdutosPOPUP(listProduto));
        }
        
        if(id!=0)
            venda.adicionarProdutoVenda(id, (int) qtd.getValue());
        
        listProdutoVenda = venda.retornaLista();
        int linha=0;
      
        //listProdutoVenda = instanciaTesteITENS();
        for (ItemDeVenda item : listProdutoVenda) {
            produto = item.getProduto();
            listaProdutos.setValueAt(produto.getQtdEstoque(), linha, 0);
            listaProdutos.setValueAt(produto.getNomeProduto(), linha, 1);
            listaProdutos.setValueAt("R$"+produto.getPreco(), linha, 2);
            listaProdutos.setValueAt("R$"+(produto.getPreco()*((int)qtd.getValue())), linha, 3);
            linha++;
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void finalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarVendaActionPerformed
        JFrame popUpPagamento = new JFrame();
        
        popUpPagamento.setSize(500, 700);        
        popUpPagamento.setTitle("Forma de Pagamento");
        popUpPagamento.setLocationRelativeTo(null); // para aparecer no meio da tela
        popUpPagamento.setVisible(true);
        
        JButton dinheiro        = new javax.swing.JButton("DINHEIRO");
        JButton cartaoCredito   = new javax.swing.JButton("CARTÃO DE CRÉDITO");
        JButton cartaoDebito    = new javax.swing.JButton("CARTÃO DE DÉBITO");
        JButton cheque          = new javax.swing.JButton("CHEQUE");
        
        dinheiro.setBounds(80,700,240, 50);
        cartaoCredito.setBounds(290,700,100, 50);
        cartaoDebito.setBounds(290,700,100, 50);
        cheque.setBounds(290,100,20, 50);

        popUpPagamento.add(dinheiro);
        /*popUpPagamento.add(cartaoCredito);
        popUpPagamento.add(cartaoDebito);
        popUpPagamento.add(cheque);*/
        
        
        JTextArea textArea = new JTextArea();
                
        
    }//GEN-LAST:event_finalizarVendaActionPerformed

    private void cancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarVendaActionPerformed
    
   
    public void starViews() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaVenda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelarVenda;
    private javax.swing.JLabel cargo;
    private javax.swing.JTextArea codDeBarrasCAMPO;
    private javax.swing.JLabel codDeBarrasLABEL;
    private javax.swing.JButton finalizarVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel listaDeCompraLABEL;
    private javax.swing.JTable listaProdutos;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JLabel nomeNomeLABEL;
    private javax.swing.JTextArea nomeTEXTO;
    private javax.swing.JSpinner qtd;
    private javax.swing.JLabel valorTotalLABEL;
    // End of variables declaration//GEN-END:variables
}
