/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entity.*;
import controller.*;
import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Set;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextArea;
import manager.*;

/**
 *
 * @author nathanbispo
 */
public class TelaVenda extends javax.swing.JFrame {
    
    ControllerVenda venda = new ControllerVenda();
    LinkedList<Produto> listProduto;
    /**
     * Creates new form OlaMundoJava
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        codDeBarras = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        codDeBarrasCAMPO = new javax.swing.JTextArea();
        nomeNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nomeTEXTO = new javax.swing.JTextArea();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cargo = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JLabel();
        qtd = new javax.swing.JSpinner();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codDeBarras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        codDeBarras.setForeground(new java.awt.Color(50, 50, 50));
        codDeBarras.setText("Cod. de Barras");
        codDeBarras.setToolTipText("");

        codDeBarrasCAMPO.setColumns(20);
        codDeBarrasCAMPO.setRows(5);
        jScrollPane2.setViewportView(codDeBarrasCAMPO);

        nomeNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeNome.setForeground(new java.awt.Color(50, 50, 50));
        nomeNome.setText("Nome");
        nomeNome.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 50, 50));
        jLabel1.setText("Lista de compras");

        nomeTEXTO.setColumns(20);
        nomeTEXTO.setRows(5);
        jScrollPane3.setViewportView(nomeTEXTO);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        listaProdutos.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        listaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Qtd", "Nome", "Preço Uni.", "Preço Parcial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listaProdutos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listaProdutos);

        jPanel1.setBackground(new java.awt.Color(0, 191, 255));

        cargo.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cargo.setForeground(new java.awt.Color(250, 250, 250));
        cargo.setText("Vendedor");

        nomeFuncionario.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        nomeFuncionario.setForeground(new java.awt.Color(250, 250, 250));
        nomeFuncionario.setText("Nome Funcionario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(512, 512, 512))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 292, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeNome)
                            .addComponent(codDeBarras))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(codDeBarras))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeNome)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar)
                    .addComponent(qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    private void buscarProdutoListaProduto(java.awt.event.ActionEvent evt, String text){
        
    }
    int linha0=1;
    private String listaProdutosPOPUP(LinkedList<Produto> list){

        //criar POPUP
        JFrame janela = new JFrame();
        JButton botao = new javax.swing.JButton("ENVIAR");
        String id = null;
        JTextArea textArea = new JTextArea();
                
        janela.setSize(500, 800);        
        janela.setTitle("Lista de Produtos");
        janela.setLocationRelativeTo(null); // para aparecer no meio da tela
        janela.setVisible(true);
  
        botao.setBounds(290,700,100, 50);
        janela.add(botao);
        textArea.setBounds(80,700,240, 50);
        janela.add(textArea);
        
        
        //add cabeçalho na primeira linha da tabela
        jTable1.setValueAt("ID", 0, 0);
        jTable1.setValueAt("NOME", 0, 1);
        jTable1.setValueAt("PREÇO", 0, 2);
        
        //coloca valores da lista na tabela jTable1
        Produto p;
        for(int i=0; i<list.size()-1; i++){
            p = list.get(i);
            jTable1.setValueAt(p.getCodigoBarras(), linha0, 0);
            jTable1.setValueAt(p.getNomeProduto(), linha0, 1);
            jTable1.setValueAt(p.getPreco(), linha0, 2);

        }
        //add tabela jTable1 no POPUP
        janela.add(jTable1);
        
        return id;
        
    }

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        int id = 0;
        Collection<ItemDeVenda> listProdutoVenda;
        Produto produto = new Produto();
        
        if(!codDeBarrasCAMPO.getText().equals("")){
           String idCampo = codDeBarrasCAMPO.getText();
           id = Integer.parseInt(idCampo);
        }
        else if(!nomeTEXTO.getText().equals("")){
            String nomeCampo = nomeTEXTO.getText();
            listProduto = venda.buscarProduto(nomeCampo);
            id = Integer.parseInt(listaProdutosPOPUP(listProduto));
        }
        
        if(id!=0)
            venda.adicionarProdutoVenda(id, (int) qtd.getValue());
        
        listProdutoVenda = venda.retornaLista();
        int linha=0;
        for (ItemDeVenda item : listProdutoVenda) {
            produto = item.getProduto();
            listaProdutos.setValueAt(produto.getQtdEstoque(), linha, 0);
            listaProdutos.setValueAt(produto.getNomeProduto(), linha, 1);
            listaProdutos.setValueAt(produto.getPreco(), linha, 2);
            listaProdutos.setValueAt((produto.getPreco()*((int)qtd.getValue())), linha, 3);
            linha++;
        }
    }                                      
    
   
    public void starViews() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaVenda().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buscar;
    private javax.swing.JLabel cargo;
    private javax.swing.JLabel codDeBarras;
    private javax.swing.JTextArea codDeBarrasCAMPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listaProdutos;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JLabel nomeNome;
    private javax.swing.JTextArea nomeTEXTO;
    private javax.swing.JSpinner qtd;
    // End of variables declaration                   
}
